name: Build & Test

on: [push]

jobs:
  build:
    name: Swift 5.9 Build & Test
    runs-on: macos-latest
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"

      - uses: actions/checkout@v4

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test
